Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MethodName:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'bin/*'
