Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*' 

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MethodName:
  Enabled: false

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/*'
    - 'db/fixtures/**/*'
    - 'tmp/**/*'
    - 'bin/*'
