version: '3.9'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: arkham
      POSTGRES_PASSWORD: arkham
      POSTGRES_DB: arkham_development
    volumes:
      - postgres_data:/var/lib/postgresql/arkham
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      bash -c "
      rm -f tmp/pids/server.pid &&
      until pg_isready -h db -p 5432 -U arkham; do sleep 1; done &&
      bundle exec rails db:create db:migrate &&
      bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      RAILS_ENV: development
      ARKHAM_DATABASE_NAME: arkham_development
      ARKHAM_DATABASE_USERNAME: arkham
      ARKHAM_DATABASE_PASSWORD: arkham
      RAILS_MAX_THREADS: 5
    volumes:
      - .:/arkham
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data: