defaults: &defaults
  filebase:
    region: 'us-east-1'
    access_key_id: <%= ENV['FILEBASE_ACCESS_KEY_ID'].to_json %>
    secret_access_key: <%= ENV['FILEBASE_SECRET_ACCESS_KEY'].to_json %>
    endpoint: 'https://s3.filebase.io'
    patient_path: patients
    bucket: 'arkham-api'
    force_path_style: true
    acl: 'public-read'
    presigned_url_expiration: 3600
  visits:
    duration: 20
  users:
    default_password: 'Arkham@2026'
    access_token_expiration: 900
    refresh_token_expiration: 2592000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  filebase:
    region: 'us-east-1'
    access_key_id: <%= ENV['FILEBASE_ACCESS_KEY_ID'].to_json %>
    secret_access_key: <%= ENV['FILEBASE_SECRET_ACCESS_KEY'].to_json %>
    endpoint: 'https://s3.filebase.io'
    patient_path: patients
    bucket: 'arkham'
    force_path_style: true
    acl: 'public-read'
    presigned_url_expiration: 3600