defaults: &defaults
  filebase:
    region: 'us-east-1'
    access_key_id: 'CB12B660B4840748F012'
    secret_access_key: 'GYftNHJUqopVTObB9JxjxTh3GDd7UKiPS2bEcZqw'
    endpoint: 'https://s3.filebase.com'
    patient_path: patients
    bucket: 'arkham'
    force_path_style: true
    acl: 'public-read'
    presigned_url_expiration: 3600
  visits:
    duration: 20
  users:
    default_password: 'Arkham@2026'
    access_token_expiration: 900
    refresh_token_expiration: 2592000

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  filebase:
    region: 'us-east-1'
    access_key_id: 'CB12B660B4840748F012'
    secret_access_key: 'GYftNHJUqopVTObB9JxjxTh3GDd7UKiPS2bEcZqw'
    endpoint: 'https://s3.filebase.com'
    patient_path: patients
    bucket: 'arkham'
    force_path_style: true
    acl: 'public-read'
    presigned_url_expiration: 3600