default: &default
  host: <%= ENV.fetch("ARKHAM_DATABASE_HOST") { "localhost" } %>
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: arkham_development
  username: arkham
  password: arkham

test:
  <<: *default
  database: arkham_test
  username: arkham
  password: arkham

production:
  <<: *default
  database: <%= ENV['ARKHAM_DATABASE_NAME'] %>
  username: <%= ENV['ARKHAM_DATABASE_USERNAME'] %>
  password: <%= ENV['ARKHAM_DATABASE_PASSWORD'] %>
